{{- range $index, $gitrepo := .Values.helmrepos }}
{{- if gt $index 0 }}
---
{{- end }}
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: {{ $gitrepo.name }}
  namespace: {{ if $gitrepo.namespace -}}{{ $gitrepo.namespace }}{{- else -}}fleet-default{{- end }}
  labels:
    app.kubernetes.io/name: {{ $gitrepo.name }}
    app.kubernetes.io/component: git-repo
    backstage.io/kubernetes-id: local
    {{- if $gitrepo.labels }}
    {{- range $key, $value := $gitrepo.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- if $gitrepo.description }}
  annotations:
    field.cattle.io/description: {{ $gitrepo.description | quote }}
  {{- end }}
spec:
  helm:
{{- toYaml $gitrepo.helm | nindent 4 }}
  {{- if $gitrepo.dependsOn }}
  dependsOn:
{{- toYaml $gitrepo.dependsOn | nindent 4 }}
  {{- end }}
  {{- if $gitrepo.targetNamespace }}
  namespace: {{ $gitrepo.targetNamespace }}
  {{- end }}
  correctDrift:
    enabled: true
  {{- if hasKey $gitrepo "keepResources" }}
  keepResources: {{ $gitrepo.keepResources }}
  {{- end }}
  {{- if ne $gitrepo.namespace "fleet-local" }}
  targets:
    {{- if $gitrepo.clusterGroups }}
    {{- range $item := $gitrepo.clusterGroups }}
    - clusterGroup: {{ $item }}
    {{- end }}
    {{- end }}
    {{- if $gitrepo.clusterSelector }}
    - name: cluster-selector
      clusterSelector:
        matchLabels:
          {{- range $key, $value := $gitrepo.clusterSelector }}
          {{ $key }}: {{ $value }}
          {{- end }}
    {{- end }}
    - clusterSelector:
        matchLabels:
          {{ $gitrepo.name }}: enabled
      name: {{ $gitrepo.name }}
    {{- if $gitrepo.targets }}
    {{- range $item := $gitrepo.targets }}
    - clusterSelector:
        matchLabels:
          {{ $item }}: enabled
      name: {{ $item }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
